name: Quarto Publish

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v3

      # Step 2: Install Quarto manually
      - name: Install Quarto
        run: |
          wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.196/quarto-linux-amd64.tar.gz
          sudo tar -xvzf quarto-linux-amd64.tar.gz -C /usr/local/bin --strip-components=1
          quarto check install

      # Step 3: Render the site
      - name: Render Site
        run: |
          quarto render

      # Step 4: Commit and Push Changes
      - name: Deploy Site
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/
          git commit -m "Automated deployment via GitHub Actions" || echo "No changes to commit"
          git push
