name: Quarto Publish

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v3

      # Step 2: Use Quarto GitHub Action
      - uses: quarto-dev/quarto-actions@v2
        with:
          target: docs

      # Step 3: Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/
          git commit -m "Automated deployment via GitHub Actions" || echo "No changes to commit"
          git push
